name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Sonarscanner for dotnet
      uses: Secbyte/dotnet-sonarscanner@v2.3
      with:
        buildCommand: dotnet build .
        testCommand: dotnet test .
        projectKey: BvR-TS-AvansDevOps
        projectName: BvR-TS-AvansDevOps
        sonarOrganisation: an-org
        sonarHostname: 'https://sonarqube.avans-informatica-breda.nl/'
        beginArguments: >
            /d:sonar.verbose="true"
            
    env:
     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
