name: 'SonarQube Analysis'
'on':
  push:
    branches:
      - master
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: philips-software/sonar-scanner-action@<version>
        with:
          token: ${{ secrets.SONARQUBE_TOKEN }}
          projectName: My Project Name
          projectKey: 'BvR-TS-AvansDevOps'
          url: '${{ secrets.SONARQUBE_HOST }}'
          isCommunityEdition: true
